apiVersion: batch/v1
kind: Job
metadata:
  name: capabilities-suite
spec:
  backoffLimit: 1
  template:
    metadata:
      name: capabilities-suite
    spec:
      containers:
        - name: tests
          image: pdstestimage
          imagePullPolicy: Always
          command:
            - "/capabilities.test"
          args:
            - -controlPlaneAPI=$(CONTROL_PLANE_API)
            - -accountName=$(ACCOUNT_NAME)
            - -tenantName=$(TENANT_NAME)
            - -projectName=$(PROJECT_NAME)
            - -issuerClientSecret=$(ISSUER_CLIENT_SECRET)
            - -issuerClientID=$(ISSUER_CLIENT_ID)
            - -issuerTokenURL=$(ISSUER_TOKEN_URL)
            - -deploymentTargetName=$(DEPLOYMENT_TARGET_NAME)
            - -pdsHelmChartVersion=$(REGISTER_SUITE_PDS_HELM_CHART_VERSION)
            - -pdsToken=$(PDS_API_TOKEN)
            - -test.failfast
            - -test.v
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - mountPath: /config
              name: helm-repository-volume
      serviceAccountName: tests-sa
      restartPolicy: Never
      volumes:
        - name: helm-repository-volume
          configMap:
            name: helm-repository