apiVersion: batch/v1
kind: Job
metadata:
  name: copilot-suite
spec:
  backoffLimit: 1
  template:
    metadata:
      name: copilot-suite
    spec:
      containers:
        - name: tests
          image: pdstestimage
          imagePullPolicy: Always
          command:
            - "/copilot.test"
          args:
            - -controlPlaneAPI=$(CONTROL_PLANE_API)
            - -issuerClientSecret=$(ISSUER_CLIENT_SECRET)
            - -issuerClientID=$(ISSUER_CLIENT_ID)
            - -issuerTokenURL=$(ISSUER_TOKEN_URL)
            - -pdsToken=$(PDS_API_TOKEN)
            - -test.failfast
            - -test.v
          envFrom:
            - configMapRef:
                name: config
      serviceAccountName: tests-sa
      restartPolicy: Never
