dataservices:
  - name: Cassandra
    versions:
      - 4.1.2
      - 4.0.10
      - 3.11.15
      - 3.0.29
  - name: Consul
    versions:
      - 1.15.3
      - 1.14.7
  - name: Couchbase
    versions:
      - 7.1.1
      - 7.2.0
  - name: Elasticsearch
    versions:
      - 8.8.0
  - name: Kafka
    versions:
      - 3.4.1
      - 3.3.2
      - 3.2.3
      - 3.1.2
  - name: MongoDB Enterprise
    versions:
      - 6.0.6
  - name: MySQL
    versions:
      - 8.0.33
  - name: PostgreSQL
    versions:
      - "15.3"
      - "14.8"
      - "13.11"
      - "12.15"
      - "11.20"
  - name: RabbitMQ
    versions:
      - 3.11.16
      - 3.10.22
  - name: Redis
    versions:
      - 7.0.9
  - name: MS SQL Server
    versions:
      - 2019-CU20
  - name: ZooKeeper
    versions:
      - 3.8.1
      - 3.7.1