FROM scratch

COPY base/ ./base
COPY dataservices/ ./dataservices
COPY dataservices/all_versions.yml ./dataservices.yml
COPY kustomization.template .
COPY repositories.yml .
COPY environment.template .
COPY helper.sh .