dataservices:
  - name: MySQL
    versions:
      - 8.0.33
  - name: PostgreSQL
    versions:
      - "15.3"
      - "14.8"
      - "13.11"
      - "12.15"
      - "11.20"
  - name: MS SQL Server
    versions:
      - 2019-CU20