name: CI Test
on:
  push:
    branches: [master]

  pull_request:

  repository_dispatch:
    types: [ci_test]

  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to test against'
        default: 'portworx/pds-infra'
        required: false
      branch:
        description: 'Branch to test against'
        default: 'ci'
        required: false
      environment:
        description: 'Environment to test against'
        default: 'dev'
        required: false
      target-api:
        description: 'Address of the target cluster API server used for registration on the control plane.'
        required: false
      target-token:
        description: 'Token of the target cluster used for registration on the control plane.'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI_REPOSITORY: ${{ github.event.inputs.repository || 'portworx/pds-infra' }}
      CI_BRANCH: ${{ github.event.inputs.branch || 'ci' }}
      CI_ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}
      TARGET_API: ${{ github.event.inputs.target-api || secrets.TARGET_API }}
      TARGET_TOKEN: ${{ github.event.inputs.target-token || secrets.TARGET_TOKEN }}
      CONTROL_PLANE_NAME: test-control-plane
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    # The kube-proxy gets stuck in a CrashLoopBackoff without the following fix:
    # https://github.com/kubernetes-sigs/kind/issues/2240
    - name: Hack - fix cluster setup
      run: sudo sysctl net/netfilter/nf_conntrack_max=131072

    # >>> Control plane setup
    - name: Control-Plane >>> Create cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
          name: ${{ env.CONTROL_PLANE_NAME }}
          # Kubernetes version
          image: kindest/node:v1.20.0

    - name: Set up Flux
      run: |
        curl -s https://fluxcd.io/install.sh | sudo bash
        flux install

    - name: Set up Flux secret
      run: echo "${{ secrets.FLUX_SECRET }}" | kubectl apply -f -

    - name: Set up SOPS GPG
      run: echo "${{ secrets.SOPS_GPG_PRIVATE }}" | kubectl create secret generic sops-gpg --namespace=flux-system --from-file=sops.asc=/dev/stdin

    - name: Set up basic auth
      id: auth
      run: |
        BASIC_AUTH_USER=pds
        BASIC_AUTH_PASSWORD=$(date +%s | sha256sum | base64 | head -c 16)
        echo "::set-output name=USER::$BASIC_AUTH_USER"
        echo "::set-output name=PASSWORD::$BASIC_AUTH_PASSWORD"
        BASIC_AUTH=$(docker run --rm marcnuri/htpasswd -Bbn "${BASIC_AUTH_USER}" "${BASIC_AUTH_PASSWORD}")
        
        cat <<EOF | kubectl apply -f -
        apiVersion: v1
        kind: Secret
        metadata:
          name: cluster-vars
          namespace: flux-system
        stringData:
          cluster_name: kind-${{ env.CONTROL_PLANE_NAME }}
          storage_class_override: standard
          basic_auth: ${BASIC_AUTH}
        EOF

    # TODO: Move the CRD template outside the workflow
    - name: Apply Git repository CRD
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: GitRepository
        metadata:
          name: flux-system
          namespace: flux-system
        spec:
          interval: 1m0s
          ref:
            branch: ${{ env.CI_BRANCH }}
          secretRef:
            name: flux-system
          url: ssh://git@github.com/${{ env.CI_REPOSITORY }}
        ---
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
        kind: Kustomization
        metadata:
          name: flux-system
          namespace: flux-system
        spec:
          interval: 10m0s
          path: ./clusters/${{ env.CI_ENVIRONMENT }}
          prune: true
          sourceRef:
            kind: GitRepository
            name: flux-system
          validation: client
        EOF

    - name: Wait for PDS deployments
      run: setup/check-deployments.sh
 
    - name: Port-forward API server
      id: port-forward
      env:
        PORT: 8888
      run: |
        kubectl port-forward svc/api-server -n pds-system ${{ env.PORT }}:80&
        API=http://localhost:${{ env.PORT }}/api
        echo "::set-output name=CONTROL_PLANE_API::${API}"

    - name: Store AWS credentials locally
      run: |
        mkdir ~/.aws
        echo "${{ secrets.AWS_CREDENTIALS }}" > ~/.aws/credentials

    # >>> Test
    - name: Test >>> Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run Test
      id: test
      # Tests rely on environment variables for connection parameters.
      run: |
        export CONTROL_PLANE_API=${{ steps.port-forward.outputs.CONTROL_PLANE_API }}
        export TARGET_API=${{ env.TARGET_API }}
        export TARGET_TOKEN=${{ env.TARGET_TOKEN }}
        go test ./... -v -json > test.json

    - name: Annotate Test
      # Quirk of the step condition evaluations: 
      # Not including `always()` is more restrictive and always evaluates to false.
      if: ${{ always() && (steps.test.outcome != 'skipped') }}
      uses: guyarb/golang-test-annotations@v0.5.0
      with:
        test-results: test.json

    # >>> Cleanup
    - name: Cleanup >>> Control plane cluster
      if: always()
      run: kind delete cluster --name ${{ env.CONTROL_PLANE_NAME }}
      
    - name: Remove AWS credentials
      if: always()
      run: rm -rf ~/.aws
