name: Code Check

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Golangci-lint
      uses: golangci/golangci-lint-action@v3.1.0
      with:
        version: v1.50.1

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint markdown files
        uses: DavidAnson/markdownlint-cli2-action@v5
        with:
          globs: |
            **/*.md
            #vendor
