name: Code Check

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
