name: Update testrail

on:
  pull_request:
  workflow_dispatch:
  # push:
  #   branches:
  #   - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
      TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3

      - name: Publish Test doc
        run: |-
          go run ./cmd/doc-publish/main.go -testrailusername ${TESTRAIL_USER} -testrailapikey ${TESTRAIL_API_KEY}
