name: Update testrail

on:
  push:
    branches:
    - main

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    env:
      TESTRAIL_USER: ${{ secrets.TESTRAIL_USER }}
      TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Publish Test doc
        run: |-
          # go run main.go -testrailusername ${TESTRAIL_USER} -testrailapikey ${TESTRAIL_API_KEY}
          make doc-publish --testrailusername ${TESTRAIL_USER} --testrailapikey ${TESTRAIL_API_KEY}
