name: Update Testrail

on:
  push:
    branches:
    - master

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Publish Test doc
        env:
          testrailusername: ${{ secrets.TESTRAIL_USER }}
          testrailapikey: ${{ secrets.TESTRAIL_API_KEY }} 
        run: |-
          make doc publish=true